name: CI/CD Pipeline

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Run unit tests
        run: |
          python3 -m unittest tests/test_app.py

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python-cli-app .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to home directory
            cd ~

            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker is not installed. Installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi
            
            # Remove old container if it exists
            docker stop python-cli-app || true
            docker rm python-cli-app || true

            # Remove old image
            docker rmi python-cli-app || true

            # Pull latest code (if applicable)
            cd ~/python-cli-app || git clone https://github.com/Shivambembey98/PyProj.git ~/python-cli-app
            cd ~/python-cli-app
            git pull origin main

            # Build and run the container
            docker build -t python-cli-app .
            docker run -d --name python-cli-app python-cli-app
          
